#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.{build}.0
install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: |
        $moduleName = 'ADDefaultLocationDsc'
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask
#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Default' `
            -CodeCoverage `
            -CodeCovIo `
            -DisableConsistency `
            -ExcludeTag @()
after_test:
  - ps: |
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorAfterTestTask `
            -ResourceModuleName $moduleName
#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask